import { parseExactJson, collect, cents, formatMoney } from './implanta-core.mjs';
import { reconcileSnapshot, snapshotCents } from './reconciliation-core.mjs';

const DMETRICS=[['orcado','Orçado'],['empenhado','Empenhado'],['liquidado','Liquidado'],['pago','Pago'],['saldoOrc','Saldo do orçamento'],['saldoLiq','A liquidar'],['saldoPagar','A pagar']];
const DMONTHS='JAN FEV MAR ABR MAI JUN JUL AGO SET OUT NOV DEZ'.split(' ');
function dEl(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function dBtn(text,fn,cls='btn'){const n=dEl('button',text,cls);n.type='button';n.addEventListener('click',fn);return n;}
function dLabel(text,control){const n=dEl('label',text);n.append(control);return n;}
function dSelect(){return dEl('select');}
function dOption(select,value,text){const n=dEl('option',text);n.value=value;select.append(n);}
function dMoney(n){return typeof n==='bigint'?formatMoney(n):'Indisponível';}
function dDate(s){return s?.split('-').reverse().join('/')||'Indisponível';}
function dStatus(s){return {match:'Valores coincidem',difference:'Divergência',missing_api:'Sem registro na API',missing_snapshot:'Sem registro no upload',invalid:'Dados incompletos',duplicate:'Chave duplicada'}[s]||s;}
function dBadge(text,status){return dEl('span',text,'lab-badge '+(status==='match'?'ok':status==='difference'||status==='invalid'||status==='duplicate'?'warn':'neutral'));}
function dTable(headers,rows){const scroll=dEl('div',undefined,'lab-table-scroll'),table=dEl('table');const head=dEl('thead'),tr=dEl('tr');headers.forEach(h=>tr.append(dEl('th',h)));head.append(tr);table.append(head);const body=dEl('tbody');for(const row of rows){const tr=dEl('tr');for(const value of row){const td=dEl('td');if(value&&typeof value==='object'&&value.nodeType)td.append(value);else td.textContent=String(value??'Indisponível');tr.append(td);}body.append(tr);}table.append(body);scroll.append(table);return scroll;}
function dDownload(name,text,mime='text/csv;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type:mime}));const a=dEl('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function dCsv(rows){return '\uFEFF'+rows.map(r=>r.map(v=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}).join(';')).join('\r\n');}
function dRatio(value,total){return typeof value==='bigint'&&typeof total==='bigint'&&total>0n?Number(value*10000n/total)/100:null;}
function dBar(value,total,label,color){const box=dEl('div',undefined,'lab-stage');const percent=dRatio(value,total);const header=dEl('div',undefined,'lab-stage-label');header.append(dEl('span',label),dEl('strong',dMoney(value)));const track=dEl('div',undefined,'lab-bar-track'),fill=dEl('div',undefined,'lab-bar-fill');fill.style.background=color;fill.style.width=percent===null?'0%':Math.min(100,Math.max(0,percent))+'%';track.append(fill);box.append(header,track,dEl('small',percent===null?'Percentual indisponível':percent.toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})+'% do orçamento'));return box;}

export function mountIntegratedDashboard(context){
 const {root,detailsRoot,accountsRoot,showPanel,readAsset,isAuthorized,getSnapshotDates,getSnapshot,centerMap,getCategories=()=>({}),getAccountAlias=n=>n}=context;
 let alive=true,revision=0,request=null,demoRecord=null,centersRecord=null,model=null,activeCenter=null,detailTab='budget',accountPage=0;
 const canUse=()=>alive&&isAuthorized();
 root.replaceChildren();detailsRoot.replaceChildren();accountsRoot.replaceChildren();
 const controls=dEl('div',undefined,'card');controls.append(dEl('h3','Posição do orçamento · API × relatório importado'));
 const fields=dEl('div',undefined,'lab-fields');const month=dEl('input');month.type='month';month.value='2026-06';month.id='labDashboardMonth';
 const date=dSelect();date.id='labDashboardDate';const refresh=dBtn('Consultar API deste mês',queryPair,'btn primary'),cancel=dBtn('Cancelar',()=>request?.abort());cancel.disabled=true;
 fields.append(dLabel('Mês da API',month),dLabel('Retrato importado',date));const actions=dEl('div',undefined,'lab-actions');actions.append(refresh,cancel);
 const status=dEl('p','Abrindo as respostas de junho verificadas…','lab-dashboard-status');status.setAttribute('role','status');status.id='labDashboardStatus';
 const provenance=dEl('div',undefined,'lab-provenance');controls.append(fields,actions,status,provenance);root.append(controls);
 const filters=dEl('details',undefined,'card lab-filter-disclosure');filters.append(dEl('summary','Filtros · categorias, busca e conferência'));const cats=dEl('div',undefined,'category-toggles');const filterFields=dEl('div',undefined,'lab-fields');const search=dEl('input');search.type='search';search.placeholder='Nome, centro ou conta';search.id='labDashboardSearch';const scope=dSelect();[['all','Todos os centros'],['difference','Somente divergências'],['missing_api','Sem registro na API'],['match','Valores coincidem']].forEach(([v,t])=>dOption(scope,v,t));const order=dSelect();[['desc','Maior saldo primeiro'],['asc','Menor saldo primeiro'],['name','Nome do centro']].forEach(([v,t])=>dOption(order,v,t));filterFields.append(dLabel('Buscar centro ou conta',search),dLabel('Conferência por centro',scope),dLabel('Ordenar saldo do orçamento',order));
 const catActions=dEl('div',undefined,'lab-actions');catActions.append(dBtn('Ligar todas',()=>{selectedCategories=null;renderFilters();renderOverview();}),dBtn('Desligar todas',()=>{selectedCategories=new Set();renderFilters();renderOverview();}),dBtn('Limpar filtros',()=>{search.value='';scope.value='all';order.value='desc';selectedCategories=null;renderFilters();renderOverview();}));filters.append(catActions,cats,filterFields);root.append(filters);
 let selectedCategories=null;
 const summary=dEl('div');summary.id='labDashboardSummary';const categorySummary=dEl('div');const centersHost=dEl('div');centersHost.id='labDashboardCenters';root.append(summary,centersHost,categorySummary);
 const dateSlider=dEl('input');dateSlider.type='range';dateSlider.id='labDashboardSlider';dateSlider.min='0';dateSlider.max='0';dateSlider.value='0';const sliderLabel=dEl('span');const sliderRow=dEl('div',undefined,'slider-row');sliderRow.append(dateSlider,sliderLabel);controls.insertBefore(sliderRow,actions);
 month.addEventListener('change',()=>{revision++;request?.abort();model=null;refreshDates();draw();});date.addEventListener('change',()=>{model=null;draw();});dateSlider.addEventListener('input',()=>{date.selectedIndex=Number(dateSlider.value);model=null;draw();});[search,scope,order].forEach(n=>n.addEventListener(n===search?'input':'change',()=>{accountPage=0;renderOverview();}));
 function refreshDates(){const old=date.value;const dates=getSnapshotDates().filter(d=>d.startsWith(month.value)).sort();date.replaceChildren();for(const d of dates)dOption(date,d,dDate(d)+(getSnapshot(d)?.origem?.labOnly?' · teste privado':''));if(dates.includes(old))date.value=old;else if(dates.length)date.value=dates.at(-1);dateSlider.max=String(Math.max(0,dates.length-1));dateSlider.disabled=dates.length<2;dateSlider.value=String(Math.max(0,date.selectedIndex));}
 function period(record){if(!record?.url)return null;const u=new URL(record.url);return {start:u.searchParams.get('referenciaInicio'),end:u.searchParams.get('referenciaTermino')};}
 function compatible(){const [y,m]=month.value.split('-');const d=period(demoRecord),c=period(centersRecord);return d?.start===`${m}/${y}`&&d?.end===`${m}/${y}`&&c?.start===`01/${y}`&&c?.end===`${m}/${y}`;}
 async function verifyAsset(id){if(!canUse())return null;const a=await readAsset(id);if(!canUse())return null;const bytes=new TextEncoder().encode(a.raw);const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('');if(!canUse())return null;if(hash!==a.sha256)throw new Error('Hash da resposta preservada não confere.');return {...a,data:parseExactJson(a.raw)};}
 async function initial(){const r=++revision;try{const demo=await verifyAsset('evidence-demonstrativo-jun2026-offline');if(!canUse()||r!==revision)return;const centers=await verifyAsset('evidence-centros-jan-jun2026');if(!canUse()||r!==revision)return;demoRecord=demo;centersRecord=centers;status.textContent='Respostas de junho verificadas. O cruzamento abaixo não altera os retratos.';draw();}catch(e){if(canUse()&&r===revision){status.textContent='Não foi possível abrir a amostra: '+e.message;draw();}}}
 async function queryPair(){if(!canUse())return;const selected=month.value;if(!/^\d{4}-\d{2}$/.test(selected)){status.textContent='Selecione um mês válido.';return;}const r=++revision;request?.abort();request=new AbortController();const signal=request.signal;refresh.disabled=true;cancel.disabled=false;status.textContent='Consultando as duas fontes: contas e centros de custo…';try{
   const demo=await collect('DemonstrativoEmpenhosPagamentos',selected,selected,null,'',signal);if(!canUse()||r!==revision)return;
   const centers=await collect('DespesasCentroCusto',selected.slice(0,4)+'-01',selected,null,'',signal);if(!canUse()||r!==revision)return;
   demoRecord={...demo,endpoint:'DemonstrativoEmpenhosPagamentos',kind:'Consulta nova'};centersRecord={...centers,endpoint:'DespesasCentroCusto',kind:'Consulta nova'};status.textContent='As duas consultas concluíram. Confira abaixo a referência, os totais e as diferenças.';model=null;draw();
  }catch(e){if(canUse()&&r===revision){status.textContent='Consulta incompleta: '+e.message+'. Os dados anteriores conservam sua referência.';draw();}}finally{if(canUse()){refresh.disabled=false;cancel.disabled=true;}request=null;}}
 function draw(){if(!canUse())return;refreshDates();const snap=getSnapshot(date.value);sliderLabel.textContent=date.value?dDate(date.value):'Sem retrato neste mês';dateSlider.value=String(Math.max(0,date.selectedIndex));provenance.replaceChildren();
   const info=dEl('div');info.append(dEl('strong','Relatório importado: '+(date.value?dDate(date.value):'não disponível')),dEl('p',snap?`${snap.origem?.arquivo||snap.origem?.formato||'Arquivo importado'} · coluna ${snap.origem?.coluna||'não informada'} · valores acumulados Na Data`:'Escolha um mês que tenha um retrato importado.','muted'));provenance.append(info);
   for(const [label,record]of [['API por conta',demoRecord],['API por centro',centersRecord]]){const info=dEl('div');const p=period(record);info.append(dEl('strong',label),dEl('p',record?`${p?.start||'?'} até ${p?.end||'?'} · consultada em ${new Date(record.collectedAt||record.collected_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} · ${record.kind||'Resposta verificada'}`:'Sem resposta para comparação','muted'));provenance.append(info);}
   if(!snap){model=null;summary.replaceChildren(dEl('div','Ainda não há retrato selecionado. As consultas continuam disponíveis na aba Consultas.','card'));centersHost.replaceChildren();categorySummary.replaceChildren();activeCenter=null;renderDetail();renderAccounts();return;}
   const pairOk=compatible();model=reconcileSnapshot(snap,pairOk?demoRecord.data:[],pairOk?centersRecord.data:[],centerMap());renderFilters();renderOverview();renderAccounts();renderDetail();
   if(!pairOk)summary.prepend(dEl('p','As respostas da API disponíveis pertencem a outro mês ou ainda não carregaram. A visão abaixo usa o upload; consulte as duas fontes para comparar esta referência.','import-warning'));
 }
 function category(center){return getCategories()?.map?.[center.label]||'Sem categoria';}
 function color(category){const value=getCategories()?.colors?.[category];return /^#[0-9a-f]{6}$/i.test(value||'')?value:'#809a74';}
 function renderFilters(){if(!model)return;const names=[...new Set(model.centers.map(category))].sort((a,b)=>a.localeCompare(b,'pt-BR'));cats.replaceChildren();for(const name of names){const check=dEl('input');check.type='checkbox';check.checked=selectedCategories===null||selectedCategories.has(name);check.addEventListener('change',()=>{if(selectedCategories===null)selectedCategories=new Set(names);if(check.checked)selectedCategories.add(name);else selectedCategories.delete(name);renderOverview();});const l=dLabel(name,check);l.className='lab-category-option';l.style.borderColor=color(name);cats.append(l);}}
 function filteredCenters(){if(!model)return[];const q=search.value.toLocaleLowerCase('pt-BR');return model.centers.filter(c=>(selectedCategories===null||selectedCategories.has(category(c)))&&(scope.value==='all'||c.status===scope.value)&&(!q||[c.label,c.code,...(c.accounts||[]).map(a=>a.code||a)].join(' ').toLocaleLowerCase('pt-BR').includes(q))).sort((a,b)=>{if(order.value==='name')return a.label.localeCompare(b.label,'pt-BR');const av=a.snapshot?.saldoOrc??0n,bv=b.snapshot?.saldoOrc??0n;return av===bv?0:av>bv?(order.value==='asc'?1:-1):(order.value==='asc'?-1:1);});}
 function totalOf(centers){const total=Object.fromEntries(DMETRICS.map(([k])=>[k,0n]));for(const [key]of DMETRICS){for(const c of centers){const v=c.snapshot?.[key];if(typeof v!=='bigint'){total[key]=null;break;}total[key]+=v;}}return total;}
 function renderOverview(){if(!model)return;summary.replaceChildren();centersHost.replaceChildren();categorySummary.replaceChildren();const selected=filteredCenters();const total=totalOf(selected.filter(c=>c.snapshot));const allVisible=selected.length===model.centers.length;
   const intro=dEl('div',undefined,'lab-overview-head');intro.append(dEl('h3','Situação atual · '+dDate(date.value)),dEl('p',`${selected.length} de ${model.centers.length} centros exibidos · saldos e barras têm origem no relatório importado`,'muted'));summary.append(intro);
   const grid=dEl('div',undefined,'lab-kpi-grid');for(const [key,title]of DMETRICS){const card=dEl('div',undefined,'card lab-kpi');card.append(dEl('span',title),dEl('strong',dMoney(total[key]),'lab-kpi-money'),dEl('small','Upload · centros visíveis'));if(allVisible&&compatible()){const av=model.totals.api?.[key],diff=model.totals.diff?.[key];card.append(dEl('p','API por conta: '+dMoney(av)),dBadge('Diferença: '+dMoney(diff),diff===0n?'match':'difference'));}else card.append(dEl('p',allVisible?'API deste mês indisponível':'API por conta é global; não há rateio validado para este filtro.','muted'));grid.append(card);}summary.append(grid);if(model.flags.some(f=>!['api_budget_zero_not_used','snapshot_rounding_policy'].includes(f.code))){const warning=dEl('div',undefined,'card lab-notice');warning.append(dEl('strong','Há dados que exigem atenção'));for(const f of model.flags.filter(f=>!['api_budget_zero_not_used','snapshot_rounding_policy'].includes(f.code)))warning.append(dEl('p',f.message));summary.append(warning);}
   const counts=dEl('div',undefined,'card lab-checks');counts.append(dEl('h3','O que o cruzamento confirma'),dEl('p','Conta contábil: compara os sete indicadores, sem somar contas sintéticas com analíticas. Centro: VALOR_TOTAL é confrontado com empenhado como hipótese de conferência; não é fonte de dotação, liquidação ou pagamento.','muted'));
   const centerCounts={match:0,difference:0,missing_api:0,invalid:0};selected.forEach(c=>centerCounts[c.status]=(centerCounts[c.status]||0)+1);const badges=dEl('div',undefined,'lab-actions');for(const [key,title]of [['match','centros com valores coincidentes'],['difference','centros divergentes'],['missing_api','centros sem registro na API'],['invalid','centros com dados incompletos']])badges.append(dBadge(`${centerCounts[key]||0} ${title}`,key));counts.append(badges,buttonLink('Examinar contas contábeis','accounts'),dBtn('Baixar conciliação dos centros (.csv)',exportCenters));summary.append(counts);
   centersHost.append(dEl('h3','Centros de custo · execução e disponibilidade'));const cards=dEl('div',undefined,'lab-centers-grid');for(const c of selected){const card=dEl('article',undefined,'card lab-center-card');card.style.borderTopColor=color(category(c));const top=dEl('div',undefined,'lab-center-head');top.append(dEl('h4',c.label),dBadge(dStatus(c.status),c.status));card.append(top,dEl('p',category(c),'lab-center-category'));const s=c.snapshot;
     if(s){card.append(dEl('p','Orçado · '+dMoney(s.orcado),'lab-center-budget'));for(const [key,title,color]of [['empenhado','Empenhado','#c4703e'],['liquidado','Liquidado','#bd994f'],['pago','Pago','#809a74']])card.append(dBar(s[key],s.orcado,title,color));const balances=dEl('div',undefined,'lab-center-balances');for(const [key,title]of DMETRICS.slice(4)){const row=dEl('div');row.append(dEl('span',title),dEl('strong',dMoney(s[key])));balances.append(row);}card.append(balances);}
     const cross=dEl('div',undefined,'lab-center-cross');cross.append(dEl('small','API por centro · execução candidata'),dEl('strong',dMoney(c.api?.candidateEmpenhado)),dEl('p','API − empenhado do upload: '+dMoney(c.executionDiff)));if(c.status==='missing_api')cross.append(dEl('p','Ausência na API não significa orçamento igual a zero.','muted'));card.append(cross,dBtn('Abrir detalhe e cruzamento',()=>openCenter(c)));cards.append(card);
   }if(!selected.length)cards.append(dEl('p','Nenhum centro corresponde aos filtros.'));centersHost.append(cards);const catsCard=dEl('div',undefined,'card');catsCard.append(dEl('h3','Resumo por categoria · relatório importado'));const names=[...new Set(selected.filter(c=>c.snapshot).map(category))].sort();const rows=names.map(name=>{const t=totalOf(selected.filter(c=>c.snapshot&&category(c)===name));return[name,...DMETRICS.map(([k])=>dMoney(t[k]))];});catsCard.append(dTable(['Categoria',...DMETRICS.map(([,n])=>n)],rows));categorySummary.append(catsCard);
 }
 function buttonLink(text,panel){return dBtn(text,()=>{if(panel==='accounts')renderAccounts();showPanel(panel);});}
 function exportCenters(){if(!canUse()||!model)return;dDownload('conciliacao-centros-'+date.value+'.csv',dCsv([['Centro','Código API','Categoria','Data upload','Referência final API','Orçado upload','Empenhado upload','Liquidado upload','Pago upload','Saldo orçamento upload','API VALOR_TOTAL (estágio pendente)','Diferença API - empenhado','Situação'],...filteredCenters().map(c=>[c.label,c.code,category(c),date.value,period(centersRecord)?.end,...['orcado','empenhado','liquidado','pago','saldoOrc'].map(k=>dMoney(c.snapshot?.[k])),dMoney(c.api?.candidateEmpenhado),dMoney(c.executionDiff),dStatus(c.status)])]));}
 function openCenter(c){activeCenter=c.code||c.label;detailTab='budget';renderDetail();showPanel('details');}
 function selectedCenter(){return model?.centers.find(c=>(c.code||c.label)===activeCenter);}
 function renderDetail(){if(!canUse())return;detailsRoot.replaceChildren();const c=selectedCenter();if(!c){const card=dEl('div',undefined,'card');card.append(dEl('h3','Detalhes do centro de custo'),dEl('p','Selecione um centro para ver orçamento, contas, execução mensal e critérios de cruzamento.'));const choose=dSelect();dOption(choose,'','Escolha um centro…');for(const item of model?.centers||[])dOption(choose,item.code||item.label,item.label);choose.addEventListener('change',()=>{activeCenter=choose.value;renderDetail();});card.append(dLabel('Centro de custo',choose));detailsRoot.append(card);return;}
   const title=dEl('div',undefined,'card');title.append(dBtn('← Voltar aos centros',()=>showPanel('dashboard')),dEl('h3',c.label),dEl('p',`Upload ${dDate(date.value)} · centro API ${c.code||'sem mapeamento'} · categoria ${category(c)}`,'muted'),dBadge(dStatus(c.status),c.status));const tabs=dEl('div',undefined,'lab-tabs');for(const [key,text]of [['budget','Orçamento'],['accounts','Contas e cruzamento'],['months','Execução por mês'],['origin','Origem e critérios']]){const b=dBtn(text,()=>{detailTab=key;renderDetail();});b.classList.toggle('primary',key===detailTab);tabs.append(b);}title.append(tabs);detailsRoot.append(title);const card=dEl('div',undefined,'card');detailsRoot.append(card);
   if(detailTab==='budget'){card.append(dEl('h3','Valores do relatório importado'),dTable(['Indicador','Upload'],DMETRICS.map(([k,n])=>[n,dMoney(c.snapshot?.[k])])),dEl('h3','Conferência com a API por centro'),dTable(['Campo','Valor'],[['VALOR_TOTAL da API',dMoney(c.api?.candidateEmpenhado)],['Empenhado do upload',dMoney(c.snapshot?.empenhado)],['Diferença API − upload',dMoney(c.executionDiff)]]),dEl('p','A API de centros não fornece dotação utilizável nesta amostra. ORCAMENTO igual a zero não substitui o orçamento do relatório. VALOR_TOTAL ainda exige confirmação do estágio contábil.','import-warning'));}
   if(detailTab==='accounts'){card.append(dEl('h3','Conta contábil × centro'),dEl('p','VALOR_TOTAL da API por centro/conta é confrontado com empenhado do upload. A API global não foi rateada. Duplicatas e ausências não recebem zero.','muted'));card.append(dTable(['Conta','Nome','Empenhado upload','Liquidado upload','Pago upload','API VALOR_TOTAL','Diferença API − upload','Conferência'],(c.accounts||[]).map(a=>[a.code,getAccountAlias(a.name),dMoney(a.snapshot?.empenhado),dMoney(a.snapshot?.liquidado),dMoney(a.snapshot?.pago),dMoney(a.apiCandidate),dMoney(a.executionDiff),dBadge(dStatus(a.status),a.status)])));}
   if(detailTab==='months'){card.append(dEl('h3','Distribuição mensal informada pela Implanta'),dEl('p','Os meses são parcelas de VALOR_TOTAL desta fonte. Não recebem os nomes liquidado ou pago; o estágio ainda não foi homologado. Meses posteriores ao recorte não são mostrados.','muted'));const endMonth=Number(month.value.slice(5,7));const points=DMONTHS.slice(0,endMonth).map((m,i)=>({label:`${String(i+1).padStart(2,'0')}/${month.value.slice(0,4)}`,value:c.api?.monthly?.[m]}));const max=points.reduce((m,p)=>typeof p.value==='bigint'&&p.value>m?p.value:m,0n);for(const p of points){const row=dEl('div',undefined,'lab-bar-row');row.append(dEl('span',p.label),dEl('strong',dMoney(p.value)));const track=dEl('div',undefined,'lab-bar-track'),fill=dEl('div',undefined,'lab-bar-fill');fill.style.width=typeof p.value==='bigint'&&p.value>=0n&&max>0n?Number(p.value*10000n/max)/100+'%':'0%';track.append(fill);row.append(track);card.append(row);}card.append(dTable(['Mês','Valor da API'],points.map(p=>[p.label,dMoney(p.value)])));}
   if(detailTab==='origin'){card.append(dEl('h3','Como os dados foram ligados'),dEl('p',`O código ${c.code||'não mapeado'} foi relacionado ao centro do relatório pelo mapeamento explícito do site, sem aproximação por nome. Conta contábil exige o código inicial do rótulo; descrições e apelidos são somente apresentação.`),dEl('p',`A API por conta usa ${period(demoRecord)?.end||'referência indisponível'}; a API por centro usa ${period(centersRecord)?.start||'?'} até ${period(centersRecord)?.end||'?'}. O upload é ${dDate(date.value)}. A igualdade numérica é uma verificação; não comprova atualização diária ou equivalência contábil universal.`),dEl('p','Valores ausentes, nulos ou duplicados não recebem zero. O orçamento é reconstruído no upload como saldo orçamentário + empenhado. Não são somados registros sintéticos e analíticos.'),dEl('h4','Alertas deste centro'));for(const flag of c.flags||[])card.append(dEl('p',typeof flag==='string'?flag:flag.message));for(const record of [demoRecord,centersRecord])if(record)card.append(dEl('p',record.url,'lab-prose'),dEl('p','SHA-256: '+record.sha256,'lab-prose'));}
 }
 const accountSearch=dEl('input');accountSearch.type='search';accountSearch.id='labAccountSearch';accountSearch.placeholder='Código ou nome da conta';const accountScope=dSelect();[['all','Todas as contas'],['difference','Divergentes'],['match','Coincidentes'],['missing_api','Ausentes na API'],['invalid','Incompletas']].forEach(([v,t])=>dOption(accountScope,v,t));accountSearch.addEventListener('input',()=>{accountPage=0;renderAccounts();});accountScope.addEventListener('change',()=>{accountPage=0;renderAccounts();});
 function renderAccounts(){if(!canUse())return;accountsRoot.replaceChildren();if(!model){accountsRoot.append(dEl('div','Selecione um retrato na Situação atual (teste).','card'));return;}const card=dEl('div',undefined,'card');card.append(dEl('h3','Conciliação por conta · '+dDate(date.value)),dEl('p','Cada conta aparece uma vez, agregando o upload por centro. A API contém apenas contas analíticas; códigos duplicados e valores incompletos são sinalizados. Selecione uma conta para os sete indicadores e centros que formam o total.','muted'));const fields=dEl('div',undefined,'lab-fields');fields.append(dLabel('Buscar conta',accountSearch),dLabel('Situação',accountScope));card.append(fields);const q=accountSearch.value.toLocaleLowerCase('pt-BR');const items=model.accounts.filter(a=>(accountScope.value==='all'||a.status===accountScope.value)&&[a.code,a.name].join(' ').toLocaleLowerCase('pt-BR').includes(q));const last=Math.max(0,Math.ceil(items.length/20)-1);accountPage=Math.min(accountPage,last);const show=items.slice(accountPage*20,accountPage*20+20);const count=items.filter(a=>a.status==='match').length;card.append(dEl('p',`${items.length} contas neste filtro · ${count} coincidem em todos os indicadores comparáveis`));card.append(dTable(['Conta','Nome','Empenhado upload','Empenhado API','Diferença','Conferência','Detalhe'],show.map(a=>[a.code,a.name,dMoney(a.snapshot?.empenhado),dMoney(a.api?.empenhado),dMoney(a.diff?.empenhado),dBadge(dStatus(a.status),a.status),dBtn('Sete indicadores',()=>renderAccountDetail(a))])));const pager=dEl('div',undefined,'lab-actions');const prev=dBtn('Anterior',()=>{accountPage--;renderAccounts();}),next=dBtn('Próxima',()=>{accountPage++;renderAccounts();});prev.disabled=accountPage===0;next.disabled=accountPage===last;pager.append(prev,dEl('span',`Página ${accountPage+1} de ${last+1}`),next,dBtn('Baixar conciliação das contas (.csv)',()=>{if(canUse())dDownload('conciliacao-contas-'+date.value+'.csv',dCsv([['Código','Conta','Indicador','Upload','API','Diferença API - upload','Conferência'],...items.flatMap(a=>DMETRICS.map(([k,n])=>[a.code,a.name,n,dMoney(a.snapshot?.[k]),dMoney(a.api?.[k]),dMoney(a.diff?.[k]),dStatus(a.status)]))]));}));card.append(pager);accountsRoot.append(card);}
 function renderAccountDetail(a){if(!canUse())return;const old=accountsRoot.querySelector('.lab-account-detail');old?.remove();const card=dEl('div',undefined,'card lab-account-detail');card.append(dEl('h3',a.code+' · '+a.name),dTable(['Indicador','Relatório importado','API por conta','API − upload'],DMETRICS.map(([k,n])=>[n,dMoney(a.snapshot?.[k]),dMoney(a.api?.[k]),dMoney(a.diff?.[k])])),dEl('h4','Centros do upload que compõem esta conta'));const rows=[];for(const [name,center]of Object.entries(getSnapshot(date.value)?.centros||{}))for(const [key,v]of Object.entries(center.contas||{}))if(key.match(/^(\d+(?:\.\d+)+)\s*(?:-|$)/)?.[1]===a.code)rows.push([name,dMoney(snapshotCents(v.Empenhado)),dMoney(snapshotCents(v.Liquidado)),dMoney(snapshotCents(v.Pago)),dMoney(snapshotCents(v.Orc_Desbloq))]);card.append(dTable(['Centro','Empenhado','Liquidado','Pago','Saldo do orçamento'],rows));accountsRoot.append(card);}
 refreshDates();draw();initial();
 return {refresh(){if(canUse()){refreshDates();draw();}},destroy(){alive=false;revision++;request?.abort();model=demoRecord=centersRecord=null;root.replaceChildren();detailsRoot.replaceChildren();accountsRoot.replaceChildren();}};
}
